replicaCount: 1

image:
  repository: 28348231.dkr.ecr.ap-south-2.amazonaws.com/test-web-app
  tag: "2"
  pullPolicy: Always

service:
  type: NodePort
  port: 3008
  nodePort: 30008

env:
  PORT: 3008
  DB_PORT: 3306
  DB_HOST: "4.440.40.44"
  DB_USER: "root"
  DB_PASSWORD: "test@123"
  DB_DATABASE: "test_app"
  JWT_SECRET: "test"
  ADMIN_NAME: "test"
  ADMIN_EMAIL: "test@gmail.com"
  ADMIN_PASSWORD: "test@123"
  PAYPAL_CLIENT_ID: "test"
  PAYPAL_CLIENT_SECRET: "test"
  PAYPAL_MODE: "sandbox"
  PLATFORM_COMMISSION_PERCENT: 10
  ESCROW_API_KEY: "test"
  ESCROW_EMAIL: "test@gmail.com"
  ESCROW_API_URL: "https://test.com"
  ESCROW_INTEGRATION_HELPER_URL: "https://test.com"
  EMAIL_USER: "test2@gmail.com"
  EMAIL_PASS: "test"
  PROJECT_ID: "test-1234"
  CLIENT_URL: "http://localhost:3000"
  STRIPE_SECRET_KEY_CLIENT: "sk_test_"
  STRIPE_SECRET_KEY: "sk_test"
  STRIPE_WEBHOOK_SECRET: "whsec_"
  PLATFORM_FEE_PERCENT: 1
  COMMISSION_PERCENT: 1
persistence:
  uploads:
    enabled: true
    existingClaim: test-app-media-pvc
    mountPath: /app/dist/uploads
  staticfiles:
    enabled: true
    existingClaim: test-app-media-pvc
    mountPath: /app/staticfiles
  media:
    enabled: true
    existingClaim: test-app-media-pvc
    mountPath: /app/media

serviceAccount:
  create: true
  name: test-app-sa

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: test.innovix.club
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

imagePullSecrets:
  - name: ecr-secret