apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skill-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "skill-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "skill-app.name" . }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-4-71.ap-south-1.compute.internal
      containers:
        - name: {{ include "skill-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence.uploads.enabled }}
            - name: uploads
              mountPath: {{ .Values.persistence.uploads.mountPath }}
            {{- end }}
            {{- if .Values.persistence.staticfiles.enabled }}
            - name: staticfiles
              mountPath: {{ .Values.persistence.staticfiles.mountPath }}
            {{- end }}
            {{- if .Values.persistence.media.enabled }}
            - name: media
              mountPath: {{ .Values.persistence.media.mountPath }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.uploads.enabled }}
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.uploads.existingClaim }}
        {{- end }}
        {{- if .Values.persistence.staticfiles.enabled }}
        - name: staticfiles
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.staticfiles.existingClaim }}
        {{- end }}
        {{- if .Values.persistence.media.enabled }}
        - name: media
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.media.existingClaim }}
        {{- end }}
